//! IPC client surface used by the PAM cdylib.
//!
//! The PAM module is sync; we therefore expose a sync `MonitorClient` trait.
//! [`MonitordClient`] talks to `tessera` over a Unix socket
//! using newline-delimited JSON frames. Each public method opens a fresh
//! socket and performs a `Hello` handshake, with a single hard time budget
//! covering connect → handshake → send → recv → close.
//!
//! [`FailModeWrapper`] adapts the typed `IpcError`s into either propagated
//! failures (`Strict`) or warnings + `Ok(())` (`Permissive`).

use std::sync::Arc;

pub mod client;
pub mod failmode;

pub use client::{ConnectPerCall, MonitorClientFactory, MonitordClient};
pub use failmode::{FailModeWrapper, MonitorFailMode};

use crate::error::IpcError;

use tessera_proto::SessionTarget;

/// Borrowed payload describing an authenticated session that monitord
/// should record.
///
/// All fields are by-reference so the PAM flow can pass already-borrowed
/// strings without copying. The consumer is expected to clone into
/// owned strings only when actually serializing the wire frame.
#[derive(Debug, Clone)]
pub struct OpenSessionInfo<'a> {
    /// Session id generated by the PAM module.
    pub session_id: &'a str,
    /// PAM user.
    pub pam_user: &'a str,
    /// PAM service.
    pub pam_service: &'a str,
    /// Hex-encoded host id hash.
    pub host_id_hash: &'a str,
    /// Where the session lives (logind id, tty path, display, ...).
    pub target: SessionTarget,
    /// USB serial that authorised the session, when available.
    pub usb_serial: Option<&'a str>,
    /// USB `VID:PID` (lowercase hex `vvvv:pppp`) of the authenticating
    /// device, when available.
    ///
    /// Passed to the daemon so credential-removal cancellation can be bound
    /// to the device's vendor/product identity rather than the cloneable
    /// USB descriptor serial. `None` for PKCS#11 tokens.
    pub usb_vid_pid: Option<&'a str>,
    /// Block-device node the credential was read from (e.g. `/dev/sdb1`),
    /// when available. Part of the same device-topology binding as
    /// [`Self::usb_vid_pid`]. `None` for PKCS#11 tokens.
    pub usb_devnode: Option<&'a str>,
    /// Common-Name from the validated end-entity certificate.
    pub cert_cn: &'a str,
    /// Hex serial of the validated end-entity certificate.
    pub cert_serial: &'a str,
    /// Lowercase hex of the engineer cert's `SubjectKeyIdentifier`.
    ///
    /// v2 IPC field — empty string when the PAM module could not extract
    /// the extension.
    pub engineer_ski: &'a str,
    /// Lowercase hex of `SHA-256(cert DER)` of the engineer leaf cert.
    ///
    /// v2 IPC field — see [`Self::engineer_ski`].
    pub engineer_cert_sha256: &'a str,
    /// Unix uid the PAM module authenticated (used by monitord to index
    /// the active-session registry).
    pub uid: u32,
    /// Role id the session was opened with (role-format). `None` when
    /// `[roles].enforce = false` or no role was selected.
    pub role: Option<&'a str>,
    /// Resolved role slice version for audit (role-format). `None` when no
    /// role was selected.
    pub role_version: Option<u32>,
    /// Absolute wall-clock instant at which a bounded role session must end —
    /// the earliest of `authenticated_at + role.session.max_ttl`,
    /// `authenticated_at + global default`, and the certificate's `notAfter`.
    /// `None` for non-role sessions, which carry no time-bound ceiling.
    ///
    /// Anchoring at the authentication instant and clamping against `notAfter`
    /// here (rather than shipping a relative TTL the daemon re-anchors at its
    /// own `opened_at`) guarantees the enforced deadline can never outlive the
    /// certificate. The daemon schedules termination directly against this
    /// instant.
    pub session_expiry: Option<std::time::SystemTime>,
}

/// Sync IPC client trait used by the PAM flow.
pub trait MonitorClient: Send + Sync {
    /// Hello / liveness probe (mostly used by self-check).
    fn hello(&self) -> Result<(), IpcError>;
    /// Notify monitord that a session has started.
    ///
    /// Carries the full payload (USB serial, session target, cert metadata)
    /// so that the daemon can perform USB-presence and removal-policy checks
    /// against accurate data. Production callers must invoke this AFTER a
    /// successful authentication so every field reflects the final verdict.
    fn open_session(&self, info: &OpenSessionInfo<'_>) -> Result<(), IpcError>;
    /// Notify monitord that a session is closing.
    fn close_session(&self, session_id: &str, reason: &str) -> Result<(), IpcError>;
    /// Liveness ping.
    fn ping(&self) -> Result<(), IpcError>;
}

/// Stub implementation kept for backwards compatibility with stage-2 callers.
///
/// All methods return `Ok(())` after emitting a debug-level log line.
pub struct StubClient;

impl MonitorClient for StubClient {
    fn hello(&self) -> Result<(), IpcError> {
        tracing::debug!(target: "tessera.ipc", "stub hello");
        Ok(())
    }

    fn open_session(&self, info: &OpenSessionInfo<'_>) -> Result<(), IpcError> {
        tracing::debug!(
            target: "tessera.ipc",
            session_id = info.session_id,
            pam_user = info.pam_user,
            pam_service = info.pam_service,
            host_id_hash = info.host_id_hash,
            usb_serial = ?info.usb_serial,
            cert_cn = info.cert_cn,
            cert_serial = info.cert_serial,
            "stub open_session"
        );
        Ok(())
    }

    fn close_session(&self, session_id: &str, reason: &str) -> Result<(), IpcError> {
        tracing::debug!(target: "tessera.ipc", session_id, reason, "stub close_session");
        Ok(())
    }

    fn ping(&self) -> Result<(), IpcError> {
        tracing::debug!(target: "tessera.ipc", "stub ping");
        Ok(())
    }
}

/// Boxed `MonitorClient` for callers that want to mix stub and real clients
/// behind a single field. Using `Arc` keeps DI cheap (no clone of state) while
/// giving the consumer the same flat API.
pub type SharedMonitorClient = Arc<dyn MonitorClient>;
