//! S13: GOST chain verification — real-fixture integration tests.
//!
//! Gated by the `gost-tests` feature.  Even with the feature on, every test
//! in this file is a no-op (prints `skipped: ...` and returns `Ok`) when the
//! fixtures generated by `tests/fixtures/gen_gost.sh` aren't present on
//! disk, or when the host doesn't ship a working `gost-engine`.
//!
//! The companion file `gost_chain_verify.rs` covers the negative invariant
//! (RSA-only chains never touch the engine `OnceLock`); this file covers the
//! positive path that requires real GOST PKI material.

#![cfg(feature = "gost-tests")]
#![allow(missing_docs)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]
#![allow(clippy::panic)]
#![allow(clippy::duration_suboptimal_units)]

mod common;

use std::time::Duration;

use tessera_core::trust::openssl_verifier::{
    OpensslVerifier, OpensslVerifierConfig, Stage2TrustVerifier,
};

use crate::common::{load_pem_cert, skip_unless_gost_ready};

fn build_verifier(anchor_pem: &str, intermediate_pem: Option<&str>, alg: &str) -> OpensslVerifier {
    let anchors = vec![load_pem_cert(anchor_pem)];
    let intermediates = match intermediate_pem {
        Some(p) => vec![load_pem_cert(p)],
        None => vec![],
    };
    OpensslVerifier::new(OpensslVerifierConfig {
        anchors,
        intermediates,
        crl_pems: vec![],
        crl_strict: false,
        crl_max_age: None,
        clock_skew: Duration::from_secs(60),
        signature_alg_whitelist: vec![alg.into()],
        spki_pins: vec![],
        max_depth: 4,
        gost_engine_path: None,
    })
    .expect("verifier ctor")
}

#[test]
fn gost256_chain_verifies_when_engine_loaded() {
    if skip_unless_gost_ready() {
        return;
    }
    let leaf = load_pem_cert("gost_ee_256.pem");
    let v = build_verifier(
        "gost_ca_256.pem",
        None,
        "id-tc26-signwithdigest-gost3410-2012-256",
    );
    let res = v.verify(&leaf, &[]);
    assert!(res.is_ok(), "GOST 2012-256 chain verify failed: {res:?}");
}

#[test]
fn gost512_chain_verifies_when_engine_loaded() {
    if skip_unless_gost_ready() {
        return;
    }
    let leaf = load_pem_cert("gost_ee_512.pem");
    let v = build_verifier(
        "gost_ca_512.pem",
        None,
        "id-tc26-signwithdigest-gost3410-2012-512",
    );
    let res = v.verify(&leaf, &[]);
    assert!(res.is_ok(), "GOST 2012-512 chain verify failed: {res:?}");
}

#[test]
fn gost_chain_rejected_when_only_rsa_in_whitelist() {
    if skip_unless_gost_ready() {
        return;
    }
    let leaf = load_pem_cert("gost_ee_256.pem");
    // Whitelist contains only RSA — pre-validation must reject the GOST leaf.
    let v = build_verifier("gost_ca_256.pem", None, "sha256WithRSAEncryption");
    let err = v
        .verify(&leaf, &[])
        .expect_err("RSA-only whitelist must reject GOST leaf");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("signature")
            || msg.contains("Signature")
            || msg.contains("algorithm")
            || msg.contains("PreValidate"),
        "unexpected reject reason: {msg}",
    );
}
