//! Client-to-daemon messages.

use std::time::SystemTime;

use uuid::Uuid;

use crate::session_target::SessionTarget;

/// Metadata captured by the PAM module at session open time.
///
/// Used as the input to [`crate::ClientMessage::SessionOpen`] so that callers
/// can pass it as a single named struct rather than ten positional arguments.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct SessionOpenPayload {
    /// Generated by the PAM module, used to correlate session events.
    pub session_id: Uuid,
    /// The Unix user the session was opened for.
    pub pam_user: String,
    /// The PAM service name (`sshd`, `login`, etc.).
    pub pam_service: String,
    /// Where the session lives (logind id, tty path, display, ...).
    pub target: SessionTarget,
    /// USB serial that authorised the session, when available.
    pub usb_serial: Option<String>,
    /// Hex-encoded host id hash.
    pub host_id_hash: String,
    /// Wall clock time the PAM module decided the session was authenticated.
    #[serde(with = "crate::system_time_serde")]
    pub opened_at: SystemTime,
    /// Common-Name from the validated end-entity certificate.
    pub cert_cn: String,
    /// Hex serial of the validated end-entity certificate.
    pub cert_serial: String,
    /// Lowercase hex of the engineer cert's `SubjectKeyIdentifier`.
    ///
    /// v2 field — clients that omit it deserialise into the empty string
    /// for backwards compatibility with v1 frames.
    #[serde(default)]
    pub engineer_ski: String,
    /// Lowercase hex of `SHA-256(cert DER)` of the engineer's leaf cert.
    ///
    /// v2 field — see [`Self::engineer_ski`].
    #[serde(default)]
    pub engineer_cert_sha256: String,
    /// Unix uid the PAM module authenticated.
    ///
    /// v2 field; `0` when omitted by a v1 client.
    #[serde(default)]
    pub uid: u32,
    // Planned (openspec/changes/role-format/): optional `role` /
    // `role_version` fields recording which role the session was opened
    // with, for audit.
}

/// Client message.
///
/// The `SessionOpen` variant is intentionally large — boxing its body
/// would only push allocation onto every send-path while saving a few
/// stack bytes on the small-variant matches. Wire ergonomics win.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
#[allow(clippy::large_enum_variant)]
pub enum ClientMessage {
    /// Initial hello — must be the first frame on any connection.
    Hello {
        /// Wire-protocol version (matches [`crate::PROTOCOL_VERSION`]).
        protocol_version: u32,
        /// Optional human-readable agent name (`libpam_tessera/0.6.0`).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agent: Option<String>,
    },
    /// Open a new session.
    SessionOpen {
        /// Session id.
        session_id: Uuid,
        /// PAM user.
        pam_user: String,
        /// PAM service.
        pam_service: String,
        /// Target session.
        target: SessionTarget,
        /// USB serial that authorised the session.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usb_serial: Option<String>,
        /// Host id hash.
        host_id_hash: String,
        /// Opened at (unix seconds).
        #[serde(with = "crate::system_time_serde")]
        opened_at: SystemTime,
        /// Cert CN.
        cert_cn: String,
        /// Cert serial (hex).
        cert_serial: String,
        /// Lowercase hex of the engineer cert `SubjectKeyIdentifier`. v2.
        #[serde(default)]
        engineer_ski: String,
        /// Lowercase hex of `SHA-256(cert DER)` of the engineer leaf. v2.
        #[serde(default)]
        engineer_cert_sha256: String,
        /// Unix uid the PAM module authenticated. v2.
        #[serde(default)]
        uid: u32,
    },
    /// Look up the active session for a given Unix uid.
    ///
    /// Returns the engineer cert metadata recorded by the daemon at PAM
    /// authentication time.
    GetActiveSessionByUid {
        /// Unix uid of the engineer's active session.
        uid: u32,
    },
    /// Close an existing session.
    SessionClose {
        /// Session id.
        session_id: Uuid,
        /// Closed at (unix seconds).
        #[serde(with = "crate::system_time_serde")]
        closed_at: SystemTime,
    },
    /// Update the `SessionTarget` of an already-open session.
    ///
    /// Sent by the PAM module from `pam_sm_open_session` once
    /// `XDG_SESSION_ID` becomes available (i.e. `pam_systemd.so` has
    /// already run in the session phase). The daemon swaps the target
    /// in-place so that subsequent USB-removal actions (Lock / Logout)
    /// can address the right logind session id.
    ///
    /// Added in 0.3.10 as a backward-compatible extension. Older daemons
    /// that do not recognise this variant reply with `BAD_REQUEST`; the
    /// PAM module logs a warning and continues — the existing entry just
    /// keeps the `Tty`/`Display`/`Unknown` target that PAM captured at
    /// authenticate time.
    UpdateSessionTarget {
        /// Session id (matches what the PAM module sent in `SessionOpen`).
        session_id: Uuid,
        /// New target (typically `SessionTarget::LogindSession { id }`).
        new_target: crate::session_target::SessionTarget,
    },
    /// Liveness check.
    Ping,
}
