#!/usr/bin/env bash
# Regenerates the OCSP fixtures in tests/fixtures/ocsp/ used by the unit
# tests of crates/tessera_core/src/ocsp/response.rs.
#
# Why pre-generated DER blobs: rust-openssl (0.10) can parse and verify
# OCSP responses but exposes no API to *build* them (OCSP_basic_add1_status
# and OCSP_basic_sign are not wrapped), so signed responses cannot be
# assembled programmatically inside the tests.  They are produced here with
# the openssl CLI from the PKI fixtures generated by gen.sh and committed
# alongside this script.  These artifacts are public test material.
#
# Requires gen.sh outputs (ca/int/leaf_*) to be present.
#
# Caveats:
#   * ocsp/expired.der is issued with nextUpdate = now + 1 minute.  Tests
#     expect it to be EXPIRED, so after regenerating wait a minute before
#     running the response.rs tests.
#   * ocsp/good*.der use -ndays 3650; they outlive ca.pem/int.pem, whose
#     expiry is the effective fixture lifetime (rerun gen.sh + this script
#     together when the PKI fixtures rotate).
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p ocsp
rm -rf ocsp_db
mkdir -p ocsp_db

# --- responder index ---------------------------------------------------
# openssl-ocsp answers from an openssl-ca index file:
#   V<TAB>expiry<TAB><TAB>serial<TAB>unknown<TAB>subject       (valid)
#   R<TAB>expiry<TAB>revdate<TAB>serial<TAB>unknown<TAB>subject (revoked)
# leaf_ecdsa is deliberately NOT listed -> the responder answers "unknown".
SERIAL_RSA=$(openssl x509 -in leaf_rsa.pem -noout -serial | cut -d= -f2)
NOW=$(date -u +%y%m%d%H%M%SZ)
EXP=$(date -u -v+365d +%y%m%d%H%M%SZ 2>/dev/null || date -u -d "+365 days" +%y%m%d%H%M%SZ)
printf 'V\t%s\t\t%s\tunknown\t/CN=alice\n' "$EXP" "$SERIAL_RSA" > ocsp_db/index.txt
printf 'R\t%s\t%s\t99\tunknown\t/CN=mallory\n' "$EXP" "$NOW" >> ocsp_db/index.txt

# Index for the intermediate, used by the root CA's responder.  The
# mode dispatcher checks every non-anchor cert in the chain, so a full
# ocsp-mode chain test needs a "good" answer for `int` too (issued by,
# and answered for by, the root `ca`).
SERIAL_INT=$(openssl x509 -in int.pem -noout -serial | cut -d= -f2)
printf 'V\t%s\t\t%s\tunknown\t/CN=CertAuth Test Intermediate\n' "$EXP" "$SERIAL_INT" > ocsp_db/index_int.txt

# --- requests ----------------------------------------------------------
# req_rsa_nonce.der keeps the CLI-generated nonce so that good_nonce.der
# (produced *for this request*) carries a matching nonce: the pair drives
# the positive nonce test, and good_nonce.der against any *fresh* request
# drives the mismatch test.
openssl ocsp -issuer int.pem -cert leaf_rsa.pem -reqout ocsp/req_rsa_nonce.der
openssl ocsp -issuer int.pem -cert leaf_rsa.pem -no_nonce -reqout ocsp/req_rsa_no_nonce.der
openssl ocsp -issuer int.pem -cert revoked_leaf.pem -no_nonce -reqout ocsp_db/req_revoked.der
openssl ocsp -issuer int.pem -cert leaf_ecdsa.pem -no_nonce -reqout ocsp_db/req_ecdsa.der
# Request for `int` relative to its own issuer (the root `ca`).
openssl ocsp -issuer ca.pem -cert int.pem -no_nonce -reqout ocsp_db/req_int.der

# --- responses signed by the issuing CA (int) --------------------------
respond() { # respond <reqin> <respout> [extra openssl-ocsp args...]
    local reqin=$1 respout=$2
    shift 2
    openssl ocsp -index ocsp_db/index.txt -CA int.pem \
        -rsigner int.pem -rkey int.key \
        -reqin "$reqin" -respout "$respout" "$@"
}

respond ocsp/req_rsa_no_nonce.der ocsp/good.der       -ndays 3650
respond ocsp/req_rsa_nonce.der    ocsp/good_nonce.der -ndays 3650
respond ocsp_db/req_revoked.der   ocsp/revoked.der    -ndays 3650
respond ocsp_db/req_ecdsa.der     ocsp/unknown.der    -ndays 3650
# Short window: expired one minute after generation.
respond ocsp/req_rsa_no_nonce.der ocsp/expired.der    -nmin 1
# No nextUpdate at all: omitting both -ndays and -nmin makes openssl emit a
# response with thisUpdate but no nextUpdate.  Such a response has no window
# to bound replay, so the verifier caps thisUpdate age instead (see
# MAX_THIS_UPDATE_AGE_WITHOUT_NEXT_UPDATE in src/ocsp/response.rs).  Fresh on
# generation, it must still verify as good.
respond ocsp/req_rsa_no_nonce.der ocsp/good_no_nextupdate.der

# --- response for the intermediate, signed by the root CA --------------
# Answers "good" for `int` (CertID built relative to `ca`); used by the
# mode-dispatcher chain tests that walk every non-anchor cert.
openssl ocsp -index ocsp_db/index_int.txt -CA ca.pem \
    -rsigner ca.pem -rkey ca.key \
    -reqin ocsp_db/req_int.der -respout ocsp/good_int.der -ndays 3650

# --- response signed by a foreign CA (must NOT verify) ------------------
# Self-signed throwaway CA outside the [trust] anchors; signs a response
# for the same CertID.  Verification must fail: its chain does not
# terminate at ca.pem.
openssl genrsa -out ocsp_db/foreign.key 2048 2>/dev/null
openssl req -x509 -new -key ocsp_db/foreign.key -sha256 -days 3650 \
    -subj "/CN=Foreign OCSP CA" \
    -config <(cat <<'EOF'
[req]
distinguished_name = dn
[dn]
EOF
) -out ocsp_db/foreign.pem
openssl ocsp -index ocsp_db/index.txt -CA int.pem \
    -rsigner ocsp_db/foreign.pem -rkey ocsp_db/foreign.key \
    -reqin ocsp/req_rsa_no_nonce.der -respout ocsp/foreign.der -ndays 3650

rm -rf ocsp_db
echo "OCSP fixtures regenerated in $(pwd)/ocsp"
