//! Per-link `basicConstraints` enforcement on a built chain.
//! See `T06` in the stage-2 plan.
//!
//! The leaf is checked elsewhere ([`super::pre_validate::pre_validate_end_entity`]):
//! this module is concerned only with positions 1..N of a leaf-first chain
//! returned by [`super::chain::build_chain`].

use std::time::{Duration, SystemTime};

use super::{Certificate, TrustError};

/// Verifies that every non-leaf certificate in `chain` is a CA and that no
/// `pathLenConstraint` is exceeded.
///
/// `chain` must be ordered leaf-first, anchor-last (the layout produced by
/// [`super::chain::build_chain`]).
///
/// # Rules
///
/// * Leaf (index 0) is **not** inspected here.
/// * Every other element must carry a `basicConstraints` extension with
///   `cA = TRUE`.  An anchor without a `basicConstraints` extension is **not**
///   accepted by this function — anchors generated by `openssl req -x509`
///   include the extension.  If you need to accept legacy anchors, supply
///   them with the extension or extend the algorithm here explicitly.
/// * If an intermediate at index `i` declares `pathLenConstraint = N`,
///   then there must be at most `N` intermediate certificates *between* it
///   and the leaf (i.e. positions `1..i`).
///
/// # Errors
///
/// * [`TrustError::PathBuild`] when `chain.len() < 2`.
/// * [`TrustError::BasicConstraints`] when any of the rules above is violated.
/// * [`TrustError::CertParse`] (propagated) on malformed `basicConstraints`.
pub fn verify_basic_constraints(chain: &[Certificate]) -> Result<(), TrustError> {
    if chain.len() < 2 {
        return Err(TrustError::PathBuild("chain too short"));
    }
    for (i, cert) in chain.iter().enumerate().skip(1) {
        let bc = cert
            .basic_constraints()?
            .ok_or(TrustError::BasicConstraints(
                "missing on intermediate/anchor",
            ))?;
        if !bc.is_ca {
            return Err(TrustError::BasicConstraints("intermediate not CA"));
        }
        if let Some(allowed) = bc.path_len {
            // Number of intermediates between this CA and the leaf.
            // For chain index `i`, indices 1..i are intermediates below it.
            let intermediates_below = i.saturating_sub(1);
            let allowed_usize = allowed as usize;
            if intermediates_below > allowed_usize {
                return Err(TrustError::BasicConstraints("pathLenConstraint exceeded"));
            }
        }
    }
    Ok(())
}

/// Validates per-link RFC 5280 constraints on every non-leaf chain element:
///
/// * `notBefore`/`notAfter` cover `now` (with `clock_skew` tolerance).
/// * `basicConstraints` is present and `cA = TRUE`.
/// * `keyUsage` is present and includes `keyCertSign` (bit 5).
///
/// `chain` must be ordered leaf-first, anchor-last. The leaf at index 0
/// is **not** inspected here — its validity / KU are covered by
/// [`super::pre_validate::pre_validate_end_entity`].
///
/// # Errors
///
/// * [`TrustError::PathBuild`] when `chain.len() < 2`.
/// * [`TrustError::Validity`] for an expired or not-yet-valid intermediate / anchor.
/// * [`TrustError::BasicConstraints`] when `basicConstraints` is missing or `cA = FALSE`.
/// * [`TrustError::KeyUsage`] when `keyUsage` is missing or lacks `keyCertSign`.
/// * [`TrustError::CertParse`] (propagated) on malformed extensions.
pub fn verify_intermediate_constraints(
    chain: &[Certificate],
    now: SystemTime,
    clock_skew: Duration,
) -> Result<(), TrustError> {
    if chain.len() < 2 {
        return Err(TrustError::PathBuild("chain too short"));
    }
    for cert in chain.iter().skip(1) {
        // Validity window with skew tolerance — symmetric with leaf
        // pre-validation.
        let nb = cert.not_before();
        let na = cert.not_after();
        if now + clock_skew < nb {
            return Err(TrustError::Validity("intermediate not yet valid"));
        }
        if now > na + clock_skew {
            return Err(TrustError::Validity("intermediate expired"));
        }

        // basicConstraints present + CA=TRUE.
        let bc = cert
            .basic_constraints()?
            .ok_or(TrustError::BasicConstraints(
                "missing on intermediate/anchor",
            ))?;
        if !bc.is_ca {
            return Err(TrustError::BasicConstraints("intermediate not CA"));
        }

        // keyUsage present + keyCertSign asserted.
        if !cert.key_usage_key_cert_sign()? {
            return Err(TrustError::KeyUsage);
        }
    }
    Ok(())
}
